# Global
server:
  servlet:
    session:
      cookie:
        http-only: false
spring:
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the JAR/WAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the
    # commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    # active: #spring.profiles.active#
    active: prod
  application:
    name: DesafioApplication
  messages:
    basename: i18n/messages
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml