version: '3.5'

services:

  db:
    build: ./postgres
    container_name:  desafio-db
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: desafio_it
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
